### ISSUE TITLE
Add support for Installment UOB

### ISSUE THREAD

**Issue by SupratikR** [omise/omise-java#142]
Please add support for installment UOB. The documentation says UOB is a supported type, but this package is yet to include it.
![image](https://user-images.githubusercontent.com/9433501/186375067-bf2a67ae-cb16-4b65-88bd-4a27aa627add.png)

**Comment by kan98** [comment]
hi @SupratikR sorry for the late reply. I've opened a PR here https://github.com/omise/omise-java/pull/143 which I'm hoping to release by today. Will update you again when it's released.

Kan

**Comment by kan98** [comment]
@SupratikR Publishing to maven repository, should appear in a few hours.
