### ISSUE TITLE
Consider dependencies alternative

### ISSUE THREAD

**Issue by kittinunf** [omise/omise-java#8]
Nice library for Omise API. Kudos for a very nice implementation.

You might wanna re-consider the dependencies that you use in the SDK. The reason for this is Omise-Java has a pretty daunting method counts. In latest version, it eats up about 35K methods count in total which is very scary. (http://www.methodscount.com/?lib=co.omise%3Aomise-java%3A2.0.7)

As you may know, Android DEX limit of method count is around 65k which is surprisingly low number. As an app developer we can't do nothing much but just to accept it. Using Omise-Java, it will almost forcefully ask app developer to resort to multi-dex option (http://www.methodscount.com/?lib=co.omise%3Aomise-java%3A2.0.7), or cut down other dependencies he/she has in the project, or even worst just to need to drop Omise-Java library itself. Those options are not an ideal for you guys.

As I have checked, google guava, and jackson lib are the top two main culprits. My suggestion to you is to find some good alternatives for them.

Thanks

**Comment by chakrit** [comment]
@kittinunf This library is not meant to be used on Android krub. It is intended for Java server implementations. We have https://github.com/omise/omise-android specifically for this.

Additionally only the tokenization process can be used from end-user devices so this library exposes too much of the API as well.

**Comment by kittinunf** [comment]
Oh I see. Well, I didn't know that you have one for Android. 

Forget about my comment then.
